development:
  adapter: postgresql
  database: imovel_dev
  username: f13
  password: f13
  host: localhost
  encoding: UTF8    

test:
  adapter: postgresql
  database: imovel_test
  username: f13
  password: f13
  encoding: UTF8

production:
  adapter: postgresql
  database: imovel_production
  username: f13
  password: f13
  host: localhost
  encoding: UTF8

